# Generated by Django 4.0.6 on 2022-10-15 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE payments_control(
            id int AUTO_INCREMENT PRIMARY KEY,
            index_payment int,
            id_agent int,
            id_payment int,
            id_insured int,
            year_made VARCHAR(4),
            month VARCHAR(15),
            commision float
            )
        """,
            reverse_sql="""
            DROP TABLE payments_control
        """,
        ),
        migrations.RunSQL(
            """
            CREATE TABLE payments_global_agency(
            id int AUTO_INCREMENT PRIMARY KEY,
            id_agent int,
            id_client int,
            id_insured int,
    		id_agency int,
            year VARCHAR(4),
            month VARCHAR(15),
    		members_number int,
            total_commission float,
            indx int
            )
        """,
            reverse_sql="""
            DROP TABLE payments_global_agency
        """,
        ),
        migrations.RunSQL(
            """
            CREATE TABLE payments_global_assistant(
            id int AUTO_INCREMENT PRIMARY KEY,
            id_agent int,
            id_client int,
            id_insured int,
    		id_state int,
    		id_assistant int,
            year VARCHAR(4),
            month VARCHAR(15),
    		members_number int,
            total_commission float,
            indx int
            )
        """,
            reverse_sql="""
            DROP TABLE payments_global_assistant
        """,
        ),
        migrations.RunSQL(
            """
            CREATE TABLE agent_portal (
            id BIGINT NOT NULL AUTO_INCREMENT, agent_id int(11), insured_id int(11),
            user VARCHAR(100), password VARCHAR(100), question1 VARCHAR(500),
            answer1 VARCHAR(500), question2 VARCHAR(500), answer2 VARCHAR(500), 
            PRIMARY KEY (id), 
            FOREIGN KEY (agent_id) REFERENCES agent(id) ON DELETE CASCADE, 
            FOREIGN KEY (insured_id) REFERENCES insured(id) ON DELETE CASCADE );
        """,
            reverse_sql="""
            DROP TABLE agent_portal
        """,
        ),
        migrations.RunSQL(
            """
            CREATE TABLE payment_excel (
            id BIGINT NOT NULL AUTO_INCREMENT,
            insured INT NULL,
            month VARCHAR(20) NULL,
            year VARCHAR(4) NULL,
            file VARCHAR(100) NULL,
            PRIMARY KEY (id))
        """,
            reverse_sql="""
            DROP TABLE payment_excel
        """,
        ),
        migrations.RunSQL(
            """
            CREATE TABLE sub_id_template (
            id BIGINT NOT NULL AUTO_INCREMENT,
            id_insured INT UNIQUE NOT NULL,
            example VARCHAR(50) NOT NULL,
            PRIMARY KEY (id))
        """,
            reverse_sql="""
            DROP TABLE sub_id_template
        """,
        ),
        migrations.RunSQL(
            """
            CREATE TABLE claim_history (
                id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
                id_claim INTEGER NOT NULL,
                claimer BOOLEAN NOT NULL,
                seen BOOLEAN NOT NULL,
                message VARCHAR(2000) NOT NULL,
                message_number INTEGER NOT NULL,
                created_at DATETIME NULL,
                file VARCHAR(100) NULL
            );
        """,
            reverse_sql="""
            DROP TABLE claim_history
        """,
        ),
        migrations.RunSQL(
            """
            CREATE TABLE original_payment(
                id BIGINT NOT NULL AUTO_INCREMENT,
                insured INT NULL,
                agent INT NULL,
                client_name VARCHAR(200) NULL,
                suscriber_id VARCHAR(200) NULL,
                state VARCHAR(20) NULL,
                npn VARCHAR(20) NULL,
                member_number INT NULL,
                effective_date DATE NULL,
                info_month VARCHAR(20) NULL,
                commission FLOAT NULL,
                new_ren VARCHAR(20) NULL,
                month VARCHAR(20) NULL,
                year VARCHAR(4) NULL,
                PRIMARY KEY(id)
            )
        """,
            reverse_sql="""
            DROP TABLE original_payment
        """,
        ),
        migrations.RunSQL(
            """
            CREATE TABLE client_medicaid (
                id BIGINT PRIMARY KEY,
                id_agent INTEGER,
                id_status INTEGER,
                name VARCHAR(100),
                lastname VARCHAR(100),
                telephone VARCHAR(20),
                address VARCHAR(100),
                email VARCHAR(50),
                access_user VARCHAR(50),
                access_password VARCHAR(50),
                ssn VARCHAR(9),
                income_source VARCHAR(4),
                employer_name VARCHAR(100),
                employer_telephone VARCHAR(100),
                alien VARCHAR(20),
                birth_country VARCHAR(100),
                notes VARCHAR(1000),
                income Float,
                approval BOOLEAN DEFAULT FALSE,
                medicare BOOLEAN DEFAULT FALSE,
                obamacare BOOLEAN DEFAULT FALSE,
                dob DATE NOT NULL,
                arrival_date DATE,
                application_date DATE,
                approval_date DATE,
                created_at DATETIME
            );
        """,
            reverse_sql="""
            DROP TABLE client_medicaid
        """,
        ),
        migrations.RunSQL(
            """
            ALTER TABLE `claim` CHANGE `date_end` `date_end` DATE NULL;
        """,
            reverse_sql="""
            ALTER TABLE `claim` CHANGE `date_end` `date_end` DATE NOT NULL;
        """,
        ),
        migrations.RunSQL(
            """
            ALTER TABLE `payments_control` ADD `created_at` DATETIME NULL DEFAULT NULL AFTER `commision`;
        """,
            reverse_sql="""
            ALTER TABLE `payments_control` drop column `created_at`;
        """,
        ),
        migrations.RunSQL(
            """
            ALTER TABLE agent_language add (id int AUTO_INCREMENT PRIMARY KEY)
        """,
            reverse_sql="""
            ALTER TABLE agent_language drop column id;
        """,
        ),
        migrations.RunSQL(
            """
            ALTER TABLE agency add (admin_id int NULL)
        """,
            reverse_sql="""
            ALTER TABLE agency drop column admin_id;
        """,
        ),
        migrations.RunSQL(
            """
            ALTER TABLE payments_global add (info_month VARCHAR(10) NULL)
        """,
            reverse_sql="""
            ALTER TABLE payments_global drop column info_month;
        """,
        ),
        migrations.RunSQL(
            """
            ALTER TABLE agent_insured add (id int AUTO_INCREMENT PRIMARY KEY)
        """,
            reverse_sql="""
            ALTER TABLE agent drop column id;
        """,
        ),
        migrations.RunSQL(
            """
            ALTER TABLE agent 
            add (
                aca tinyint(1),
                aca_date_certification date,
                aca_certificate_number varchar(200),
                napa_date_certification date,
                napa_certificate_number varchar(200),
                napa tinyint(1),
                cms tinyint(1),
                sherpa tinyint(1),
                fields longtext,
                id_commission_group BIGINT(20) NULL DEFAULT NULL
            )
        """,
            reverse_sql="""
            ALTER TABLE agent drop column aca;
            ALTER TABLE agent drop column aca_date_certification;
            ALTER TABLE agent drop column aca_certificate_number;
            ALTER TABLE agent drop column napa_date_certification;
            ALTER TABLE agent drop column napa_certificate_number;
            ALTER TABLE agent drop column napa;
            ALTER TABLE agent drop column cms;
            ALTER TABLE agent drop column sherpa;
            ALTER TABLE agent drop column fields;
            ALTER TABLE agent drop column borrado;
            ALTER TABLE agent drop column id_commission_group;
        """,
        ),
        migrations.RunSQL(
            """
            ALTER TABLE insured 
            add (
                logo varchar(60)
            )
        """,
            reverse_sql="""
            ALTER TABLE insured drop column logo;
        """,
        ),
        migrations.RunSQL(
            """
            DELETE t1 FROM agent t1
            INNER JOIN agent t2 
            WHERE t1.id > t2.id AND t1.email = t2.email; 

            DELETE t1 FROM assistant t1
            INNER JOIN assistant t2 
            WHERE t1.id > t2.id AND t1.email = t2.email; 

            DELETE t1 FROM subassistant t1
            INNER JOIN subassistant t2 
            WHERE t1.id > t2.id AND t1.email = t2.email; 

            DELETE t2 FROM agent t1
            INNER JOIN assistant t2 
            WHERE t1.email = t2.email; 

            DELETE t2 FROM agent t1
            INNER JOIN subassistant t2 
            WHERE t1.email = t2.email; 

            DELETE t1 FROM subassistant t1
            INNER JOIN assistant t2 
            WHERE t1.email = t2.email; 
        """
        ),
        migrations.RunSQL(
            """
            INSERT INTO auth_group values(NULL,'Agent')
        """,
            reverse_sql="""
            Delete from auth_group WHERE id=1
        """,
        ),
        migrations.RunSQL(
            """
            INSERT INTO auth_group values(NULL,'Assistant')
        """,
            reverse_sql="""
            Delete from auth_group WHERE id=2
        """,
        ),
        migrations.RunSQL(
            """
            INSERT INTO auth_group values(NULL,'SubAssistant')
        """,
            reverse_sql="""
            Delete from auth_group WHERE id=3
        """,
        ),
        migrations.RunSQL(
            """
            INSERT INTO customauth_customuser (
                id,
                username,
                password,
                email,
                is_agent,
                is_active,
                last_login,
                is_superuser,
                first_name,
                last_name,
                is_staff,
                date_joined,
                is_admin,
                is_assistant,
                is_subassistant
            )
            SELECT
                NULL,
                email,
                password,
                email,
                TRUE,
                TRUE,
                NULL,
                FALSE,
                agent_name,
                agent_lastname,
                FALSE,
                '1980-01-01',
                FALSE,
                FALSE,
                FALSE
            FROM
                agent;
        """,
            reverse_sql="""
            DELETE FROM customauth_customuser WHERE is_agent=1
        """,
        ),
        migrations.RunSQL(
            """
            INSERT INTO customauth_customuser (
                id,
                username,
                password,
                email,
                is_assistant,
                is_active,
                last_login,
                is_superuser,
                first_name,
                last_name,
                is_staff,
                date_joined,
                is_admin,
                is_agent,
                is_subassistant
            )
            SELECT
                NULL,
                email,
                password,
                email,
                TRUE,
                TRUE,
                NULL,
                FALSE,
                assistant_name,
                assistant_lastname,
                FALSE,
                '1980-01-01',
                FALSE,
                FALSE,
                FALSE
            FROM
                assistant;
        """,
            reverse_sql="""
            DELETE FROM customauth_customuser WHERE is_assistant=1
        """,
        ),
        migrations.RunSQL(
            """
            INSERT INTO customauth_customuser (
                id,
                username,
                password,
                email,
                is_subassistant,
                is_active,
                last_login,
                is_superuser,
                first_name,
                last_name,
                is_staff,
                date_joined,
                is_admin,
                is_agent,
                is_assistant
            )
            SELECT
                NULL,
                email,
                password,
                email,
                TRUE,
                TRUE,
                NULL,
                FALSE,
                assistant_name,
                assistant_lastname,
                FALSE,
                '1980-01-01',
                FALSE,
                FALSE,
                FALSE
            FROM
                subassistant;
        """,
            reverse_sql="""
            DELETE FROM customauth_customuser WHERE is_subassistant=1
        """,
        ),
        migrations.RunSQL(
            """
            CREATE TABLE `agent_commission` (
                `id` bigint(20) NOT NULL AUTO_INCREMENT,
                `id_insured` int(11) NOT NULL,
                `id_state` int(11) NOT NULL,
                `comm_new` decimal(10,2) DEFAULT 0.00,
                `comm_rew` decimal(10,2) DEFAULT 0.00,
                `comm_set` decimal(10,2) DEFAULT 0.00,
                `comm_set2` decimal(10,2) DEFAULT 0.00,
                `yearcom` varchar(4) NOT NULL,
                `id_agent` int(15) NOT NULL,
                PRIMARY KEY (`id`),
                UNIQUE KEY `AgentComm C1` (`id_insured`,`id_state`,`id_agent`,`yearcom`),
                KEY `agent_commission_ibfk_1` (`id_agent`),
                CONSTRAINT `agent_commission_ibfk_1` FOREIGN KEY (`id_agent`) REFERENCES `agent` (`id`)
                );
        """,
            reverse_sql="""
            DROP TABLE agent_commission
        """,
        ),
        migrations.RunSQL(
            """
           CREATE TABLE `commissions_group` (
                `id` bigint(20) NOT NULL AUTO_INCREMENT,
                `names` varchar(50) NOT NULL,
                PRIMARY KEY (`id`)
                );
        """,
            reverse_sql="""
            DROP TABLE commissions_group
        """,
        ),
        migrations.RunSQL(
            """
           CREATE TABLE `group_commission` (
                `id` bigint(20) NOT NULL AUTO_INCREMENT,
                `id_insured` int(11) NOT NULL,
                `id_state` int(11) NOT NULL,
                `comm_new` decimal(10,2) DEFAULT 0.00,
                `comm_rew` decimal(10,2) DEFAULT 0.00,
                `comm_set` decimal(10,2) DEFAULT 0.00,
                `comm_set2` decimal(10,2) DEFAULT 0.00,
                `yearcom` varchar(4) NOT NULL,
                `id_group` bigint(20) NOT NULL,
                PRIMARY KEY (`id`),
                UNIQUE KEY `GroupComm C1` (`id_insured`,`id_state`,`id_group`,`yearcom`),
                KEY `group_commission_id_group_7f3417e0_fk_commissions_group_id` (`id_group`),
                CONSTRAINT `group_commission_id_group_7f3417e0_fk_commissions_group_id` FOREIGN KEY (`id_group`) REFERENCES `commissions_group` (`id`)
                );
        """,
            reverse_sql="""
            DROP TABLE group_commission
        """,
        ),
        migrations.RunSQL(
            """
           CREATE TABLE temp_sms_file (
                id bigint(20) NOT NULL AUTO_INCREMENT,
                file varchar(50) NOT NULL,
                created date NOT NULL,
                PRIMARY KEY (id)
            );
        """,
            reverse_sql="""
            DROP TABLE temp_sms_file
        """,
        ),
        migrations.RunSQL(
            """
           CREATE TABLE `client_log` (
                `id` bigint(20) NOT NULL AUTO_INCREMENT,
                `added_on` datetime(6) NOT NULL,
                `type` varchar(20) NOT NULL,
                `user_id` bigint(20) DEFAULT NULL,
                `client_id` int(11) DEFAULT NULL,
                PRIMARY KEY (`id`),
                KEY `user_id` (`user_id`),
                KEY `client_id` (`client_id`),
                CONSTRAINT `client_log_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `customauth_customuser` (`id`),
                CONSTRAINT `client_log_ibfk_2` FOREIGN KEY (`client_id`) REFERENCES `client` (`id`)
            );
        """,
            reverse_sql="""
            DROP TABLE client_log;
        """,
        ),
        migrations.RunSQL(
            """
           CREATE TABLE agent_payments (
                id BIGINT PRIMARY KEY AUTO_INCREMENT,
                id_agent INT NOT NULL,
                id_client INT NOT NULL,
                id_insured INT NOT NULL,
                id_state INT NOT NULL,
                year CHAR(4) NOT NULL,
                month CHAR(15) NOT NULL,
                info_month CHAR(15) NOT NULL,
                repaid_on CHAR(15) NULL DEFAULT NULL,
                payment_type CHAR(15) NOT NULL,
                agent_name VARCHAR(200) DEFAULT '',
                client_name VARCHAR(200) DEFAULT '',
                insured_name VARCHAR(200) DEFAULT '',
                suscriberid VARCHAR(50) NOT NULL,
                members_number INT NOT NULL,
                payment_index INT NOT NULL,
                commission FLOAT NOT NULL,
                created_at DATETIME DEFAULT NULL
            )
        """,
            reverse_sql="""
            DROP TABLE agent_payments;
        """,
        ),
        migrations.RunSQL(
            """
           CREATE TABLE client_consent_log (
                id BIGINT PRIMARY KEY AUTO_INCREMENT,
                id_agent INT NOT NULL,
                id_client INT NOT NULL,
                client_name VARCHAR(100) DEFAULT '',
                agent_name VARCHAR(100) DEFAULT '',
                year CHAR(4) NOT NULL,
                sended BOOLEAN NULL DEFAULT NULL,
                signed BOOLEAN NULL DEFAULT NULL,

                lan VARCHAR(2) NULL,
                client_dob VARCHAR(15) NULL,
                client_tel VARCHAR(20) NULL,
                client_email VARCHAR(50) NULL,
                main_agent_npn VARCHAR(15) NULL,
                main_agent_tel VARCHAR(15) NULL,
                main_agent_name VARCHAR(100) NULL,
                secondary_agent_npn VARCHAR(15) NULL,
                secondary_agent_tel VARCHAR(15) NULL,
                secondary_agent_name VARCHAR(100) NULL,
                date_sended DATETIME NULL,
                date_signed DATETIME NULL,
                secret_key VARCHAR(100) NULL
            )
        """,
            reverse_sql="""
            DROP TABLE client_consent_log;
        """,
        ),
        migrations.RunSQL(
            """
            CREATE TABLE agent_global_ce (
                id BIGINT PRIMARY KEY AUTO_INCREMENT,
                npn VARCHAR(30) not null,
                ce_due_date VARCHAR(50) NULL,
                ce_req_hours VARCHAR(50) NULL,
                ce_completed_hours VARCHAR(50) NULL
            )
        """,
            reverse_sql="""
            DROP TABLE agent_global_ce;
        """,
        ),
        migrations.RunSQL(
            """
           CREATE TABLE agent_global_appointment (
                id BIGINT PRIMARY KEY AUTO_INCREMENT,
                npn VARCHAR(30) not null,
                agent_name VARCHAR(300),
                license_num VARCHAR(30),
                business_address VARCHAR(1000),
                mailing_address VARCHAR(1000),
                county VARCHAR(30),
                email VARCHAR(100),
                phone VARCHAR(15),
                company_name VARCHAR(200),
                issue_date VARCHAR(50),
                exp_date VARCHAR(50),
                app_type VARCHAR(100),
                app_code VARCHAR(50),
                active_or_not BOOLEAN
            )
        """,
            reverse_sql="""
            DROP TABLE agent_global_appointment;
        """,
        ),
        migrations.RunSQL(
            """
           CREATE TABLE agent_global_license (
                id BIGINT PRIMARY KEY AUTO_INCREMENT,
                npn VARCHAR(30) not null,
                license_type VARCHAR(100) NULL,
                license_issue_date VARCHAR(50) NULL,
                license_code VARCHAR(50) NULL,
                license_active_or_not BOOLEAN NULL
            )
        """,
            reverse_sql="""
            DROP TABLE agent_global_license;
        """,
        ),
        migrations.RunSQL(
            """
           CREATE TABLE repayments (
                id BIGINT PRIMARY KEY AUTO_INCREMENT,
                id_agent INT NOT NULL,
                id_client INT NOT NULL,
                id_insured INT NOT NULL,
                id_state INT NOT NULL,
                year CHAR(4) NOT NULL,
                month CHAR(15) NOT NULL,
                info_month CHAR(15) NOT NULL,
                payment_type CHAR(15) NOT NULL,
                agent_name VARCHAR(200) DEFAULT '',
                client_name VARCHAR(200) DEFAULT '',
                insured_name VARCHAR(200) DEFAULT '',
                suscriberid VARCHAR(50) NOT NULL,
                members_number INT NOT NULL,
                payment_index INT NOT NULL,
                commission FLOAT NOT NULL,
                created_at DATETIME DEFAULT NULL
            )
        """,
            reverse_sql="""
            DROP TABLE repayments;
        """,
        ),
        migrations.RunSQL(
            """
            CREATE TABLE override (
                id BIGINT PRIMARY KEY AUTO_INCREMENT,
                id_insured INT NOT NULL,
                year CHAR(4) NOT NULL,
                state CHAR(15) NOT NULL,
                month CHAR(15) NOT NULL,
                info_month CHAR(15) NOT NULL,
                payment_type CHAR(15) NOT NULL,
                agent_name VARCHAR(200) DEFAULT '',
                client_name VARCHAR(200) DEFAULT '',
                insured_name VARCHAR(200) DEFAULT '',
                suscriberid VARCHAR(50) NOT NULL,
                members_number INT NOT NULL,
                commission FLOAT NOT NULL,
                created_at DATETIME DEFAULT NULL
            )
        """,
            reverse_sql="""
            DROP TABLE override;
        """,
        ),
        migrations.RunSQL(
            """
           CREATE TABLE future_payments (
                id BIGINT PRIMARY KEY AUTO_INCREMENT,
                id_agent INT NOT NULL,
                id_client INT NOT NULL,
                id_insured INT NOT NULL,
                id_state INT NOT NULL,
                year CHAR(4) NOT NULL,
                month CHAR(15) NOT NULL,
                info_month CHAR(15) NOT NULL,
                payment_type CHAR(15) NOT NULL,
                agent_name VARCHAR(200) DEFAULT '',
                client_name VARCHAR(200) DEFAULT '',
                insured_name VARCHAR(200) DEFAULT '',
                suscriberid VARCHAR(50) NOT NULL,
                members_number INT NOT NULL,
                payment_index INT NOT NULL,
                commission FLOAT NOT NULL,
                created_at DATETIME DEFAULT NULL
            )
        """,
            reverse_sql="""
            DROP TABLE future_payments;
        """,
        ),

        migrations.RunSQL(
            """
            CREATE TABLE agency_repayment(
            id int AUTO_INCREMENT PRIMARY KEY,
            id_agent int,
            id_client int,
            id_insured int,
    		id_agency int,
            year VARCHAR(4),
            month VARCHAR(15),
            info_month VARCHAR(15) NULL,
    		members_number int,
            total_commission float,
            indx int,
            created_at DATETIME
            )
        """,
            reverse_sql="""
            DROP TABLE agency_repayment
        """,
        ),
        migrations.RunSQL(
            """
            CREATE TABLE unassigned_payments(
                id int AUTO_INCREMENT PRIMARY KEY,
                id_insured int NULL,
                client_name VARCHAR(100) NULL,
                agent_name VARCHAR(100) NULL,
                state_initials VARCHAR(2) NULL,
                suscriberid VARCHAR(50) NULL,
                month VARCHAR(15),
                info_month VARCHAR(15) NULL,
                year VARCHAR(4) NULL,
                new_ren VARCHAR(15) NULL,
                npn VARCHAR(20) NULL,
                members int NULL,
                rate float NULL,
                commission float NULL,
                effective_date DATE NULL,
                created_at DATETIME
            )
        """,
            reverse_sql="""
            DROP TABLE unassigned_payments
        """,
        ),
        migrations.RunSQL(
            """
            CREATE TABLE secondary_override (
                id BIGINT NOT NULL AUTO_INCREMENT, 
                id_insured int NULL, 
                id_parent_agency int NULL,
                id_children_agency int NULL,
                amount_per_member float NULL, 
                PRIMARY KEY (id), 
                FOREIGN KEY (id_insured) REFERENCES insured(id) ON DELETE CASCADE, 
                FOREIGN KEY (id_parent_agency) REFERENCES agency(id) ON DELETE CASCADE,
                FOREIGN KEY (id_children_agency) REFERENCES agency(id) ON DELETE CASCADE 
            )
        """,
            reverse_sql="""
            DROP TABLE secondary_override
        """,
        ),
        migrations.RunSQL(
            """
           CREATE TABLE income_letter_log (
                id BIGINT PRIMARY KEY AUTO_INCREMENT,
                id_client INT NOT NULL,
                id_agent INT NOT NULL,
                client_name VARCHAR(100) DEFAULT '',
                agent_name VARCHAR(100) DEFAULT '',
                year CHAR(4) NOT NULL,
                sended BOOLEAN NULL DEFAULT NULL,
                signed BOOLEAN NULL DEFAULT NULL,

                lan VARCHAR(2) NULL,
                client_dob VARCHAR(15) NULL,
                client_tel VARCHAR(20) NULL,
                date_sended DATETIME NULL,
                date_signed DATETIME NULL,
                application_id VARCHAR(30) NULL,
                ssn VARCHAR(20) NULL,
                address VARCHAR(300) NULL,
                income FLOAT NULL,
                secret_key VARCHAR(100) NULL
            )
        """,
            reverse_sql="""
            DROP TABLE income_letter_log;
        """,
        ),
        migrations.RunSQL(
            """
           CREATE TABLE pre_letter_log (
                id BIGINT PRIMARY KEY AUTO_INCREMENT,
                id_agent INT NOT NULL,
                client_name VARCHAR(100) DEFAULT '',
                year CHAR(4) NOT NULL,
                sended BOOLEAN NULL DEFAULT NULL,
                signed BOOLEAN NULL DEFAULT NULL,

                lan VARCHAR(2) NULL,
                client_dob VARCHAR(15) NULL,
                client_tel VARCHAR(20) NULL,
                client_email VARCHAR(200) NULL,
                agent_name VARCHAR(100) NULL,
                agent_npn VARCHAR(20) NULL,
                agent_phone VARCHAR(20) NULL,
                date_sended DATETIME NULL,
                date_signed DATETIME NULL,
                file VARCHAR(100) NULL,
                secret_key VARCHAR(100) NULL
            )
        """,
            reverse_sql="""
            DROP TABLE pre_letter_log;
        """,
        ),
        migrations.RunSQL(
            """
           CREATE TABLE agent_state (
                id BIGINT NOT NULL AUTO_INCREMENT, 
                id_agent int NOT NULL, 
                id_state int NOT NULL,
                PRIMARY KEY (id), 
                FOREIGN KEY (agent) REFERENCES agent(id) ON DELETE CASCADE, 
                FOREIGN KEY (state) REFERENCES state(id) ON DELETE CASCADE
            )
        """,
            reverse_sql="""
            DROP TABLE agent_state;
        """,
        ),
        migrations.RunSQL(
            """
            CREATE TABLE self_managed_agency_payment(
                id int AUTO_INCREMENT PRIMARY KEY,
                id_insured int NULL,
                id_state int NULL,
                id_agent int NULL,
                id_client int NULL,
                id_agency int NULL,

                year VARCHAR(4) NULL,
                month VARCHAR(15),
                info_month VARCHAR(15) NULL,
                payment_type VARCHAR(15) NULL,
                client_name VARCHAR(100) NULL,
                insured_name VARCHAR(200) NULL,
                agent_name VARCHAR(100) NULL,
                agency_name VARCHAR(100) NULL,
                suscriberid VARCHAR(50) NULL,
                members_number int NULL,
                commission float NULL,
                created_at DATETIME
            )
        """,
            reverse_sql="""
            DROP TABLE self_managed_agency_payments
        """,
        ),
        migrations.RunSQL(
            """
            CREATE TABLE pdf_notices (
                id BIGINT NOT NULL AUTO_INCREMENT, 
                name VARCHAR(100) NOT NULL, 
                file VARCHAR(500) NOT NULL,
                created_at DATETIME,
                PRIMARY KEY (id)
            )
        """,
            reverse_sql="""
            DROP TABLE pdf_notices;
        """,
        ),
        migrations.RunSQL(
            """
            CREATE TABLE problems (
                id BIGINT NOT NULL AUTO_INCREMENT, 
                names VARCHAR(100) NOT NULL,
                PRIMARY KEY (id)
            )
        """,
            reverse_sql="""
            DROP TABLE problems;
        """,
        ),
        migrations.RunSQL(
            """
            CREATE TABLE application_problems (
                id BIGINT NOT NULL AUTO_INCREMENT, 
                id_client BIGINT NOT NULL,
                id_problem BIGINT NOT NULL,
                PRIMARY KEY (id)
            )
        """,
            reverse_sql="""
            DROP TABLE application_problems;
        """,
        ),
        migrations.RunSQL(
            """
            CREATE TABLE agent_tax_document (
                id BIGINT NOT NULL AUTO_INCREMENT, 
                id_agent BIGINT NOT NULL,
                file VARCHAR(500) NULL,
                PRIMARY KEY (id)
            )
        """,
            reverse_sql="""
            DROP TABLE agent_tax_document;
        """,
        ),
        migrations.RunSQL(
            """
           update customauth_customuser c join
           (select sq.email, sq.telephone from (select a.email,a.telephone from agent a where a.telephone!='' union select a.email,a.telephone from assistant a where a.telephone!='')sq group by sq.telephone) j 
           on c.email = j.email
           set c.personal_phone_number = j.telephone
        """,
            reverse_sql="""
            update customauth_customuser c set c.personal_phone_number = null
        """,
        ),
        migrations.RunSQL(
            """
           ALTER TABLE `claim` CHANGE `date_begin` `date_begin` DATE NULL;
        """,
            reverse_sql="""
            ALTER TABLE `claim` CHANGE `date_begin` `date_begin` DATE;
        """,
        ),
        migrations.RunSQL(
            """
           ALTER TABLE `agent` CHANGE `agent_name` `agent_name` VARCHAR(50) CHARACTER SET utf8mb3 COLLATE
           utf8mb3_general_ci NULL, CHANGE `agent_lastname` `agent_lastname` VARCHAR(50) CHARACTER SET utf8mb3
           COLLATE utf8mb3_general_ci NULL, CHANGE `id_assistant` `id_assistant` INT NULL, CHANGE `comments`
           `comments` VARCHAR(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `license_number`
           `license_number` VARCHAR(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `id_county`
           `id_county` INT NULL, CHANGE `npn` `npn` VARCHAR(15) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL,
           CHANGE `telephone` `telephone` VARCHAR(15) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE
           `email` `email` VARCHAR(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `email2` `email2`
           VARCHAR(150) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `agent_number` `agent_number`
           VARCHAR(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `humana_san` `humana_san`
           VARCHAR(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `password` `password` TEXT
           CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `core` `core` VARCHAR(10) CHARACTER
           SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `relase_requiered` `relase_requiered` INT NULL,
           CHANGE `relase_coment` `relase_coment` VARCHAR(250) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL,
           CHANGE `ahip` `ahip` INT NULL, CHANGE `ahip_date_start` `ahip_date_start` DATE NULL,
           CHANGE `ahip_date_renewal` `ahip_date_renewal` DATE NULL, CHANGE `administrator` `administrator`
           INT NULL, CHANGE `des_renewal` `des_renewal` DECIMAL(15,0) NULL, CHANGE `des_oep` `des_oep`
           DECIMAL(15,0) NULL, CHANGE `document` `document` VARCHAR(60) CHARACTER SET utf8mb3 COLLATE
           utf8mb3_general_ci NULL, CHANGE `typepay` `typepay` INT NULL, CHANGE `id_agency` `id_agency` INT NULL,
           CHANGE `id_group` `id_group` INT NULL DEFAULT '0', CHANGE `id_group2` `id_group2` INT NULL DEFAULT '0',
           CHANGE `adminagency` `adminagency` INT NULL, CHANGE `telephone2` `telephone2` VARCHAR(15)
           CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `socialsecurity` `socialsecurity`
           VARCHAR(15) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `adreess` `adreess`
           VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `passSherpa` `passSherpa`
           VARCHAR(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `user1Sherpa` `user1Sherpa`
           VARCHAR(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `user2Sherpa` `user2Sherpa`
           VARCHAR(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `pass2Sherpa` `pass2Sherpa`
           VARCHAR(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `userCMS` `userCMS`
           VARCHAR(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `passCMS` `passCMS`
           VARCHAR(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `pregunta` `pregunta`
           VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `pregunta1` `pregunta1`
           VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `pregunta2` `pregunta2`
           VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `date_start` `date_start`
           DATE NULL, CHANGE `date_birth` `date_birth` DATE NULL, CHANGE `back_name` `back_name` VARCHAR(30)
           CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `router_number` `router_number` VARCHAR(30)
           CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `back_account` `back_account` VARCHAR(30)
           CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `type_account` `type_account` INT NULL,
           CHANGE `polyce_number` `polyce_number` VARCHAR(30) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL,
           CHANGE `efective_certificate` `efective_certificate` DATE NULL, CHANGE `end_certificate`
           `end_certificate` DATE NULL, CHANGE `borrado` `borrado` INT NULL;
        """,
            reverse_sql="""
            
        """,
        ),
        migrations.RunSQL(
            """
           ALTER TABLE `client` CHANGE `names` `names` VARCHAR(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci
           NULL, CHANGE `lastname` `lastname` VARCHAR(150) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL,
           CHANGE `suscriberid` `suscriberid` VARCHAR(15) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL,
           CHANGE `aplication_date` `aplication_date` DATE NULL, CHANGE `id_insured` `id_insured` INT NULL,
           CHANGE `date_birth` `date_birth` DATE NULL, CHANGE `telephone` `telephone` VARCHAR(15)
           CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `email` `email` VARCHAR(150)
           CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `id_agent` `id_agent` INT NULL,
           CHANGE `pending` `pending` INT NULL, CHANGE `new_ren` `new_ren` INT NULL, CHANGE `agent2` `agent2`
           VARCHAR(150) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `id_status` `id_status`
           INT NULL, CHANGE `income` `income` INT NULL, CHANGE `migratory_status` `migratory_status` INT NULL,
           CHANGE `social_security_doc` `social_security_doc` INT NULL, CHANGE `loss_medicaiad` `loss_medicaiad`
           INT NULL, CHANGE `pendingno` `pendingno` INT NULL, CHANGE `borrado` `borrado` INT NULL, CHANGE `coverage`
           `coverage` INT NULL, CHANGE `sexo` `sexo` INT NULL, CHANGE `princome` `princome` VARCHAR(50) CHARACTER SET
           utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `priw21099` `priw21099` INT NULL, CHANGE `conincome`
           `conincome` VARCHAR(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `teltrabajo`
           `teltrabajo` VARCHAR(30) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `nomtrabajo`
           `nomtrabajo` VARCHAR(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `totalincome`
           `totalincome` VARCHAR(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `aproxmontpay`
           `aproxmontpay` VARCHAR(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `plansupp`
           `plansupp` VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `payment`
           `payment` FLOAT(12,2) NULL, CHANGE `usermark` `usermark` VARCHAR(100) CHARACTER SET utf8mb3 COLLATE
           utf8mb3_general_ci NULL, CHANGE `usermarkpw` `usermarkpw` VARCHAR(100) CHARACTER SET utf8mb3
           COLLATE utf8mb3_general_ci NULL, CHANGE `mensualidad` `mensualidad` FLOAT(12,2) NULL, CHANGE `targeta`
           `targeta` INT NULL, CHANGE `targetatipo` `targetatipo` INT NULL, CHANGE `ccnumber` `ccnumber`
           VARCHAR(25) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `expdate` `expdate`
           VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `cvccode` `cvccode`
           INT NULL, CHANGE `toname` `toname` VARCHAR(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL,
           CHANGE `billingaddreess` `billingaddreess` VARCHAR(250) CHARACTER SET utf8mb3 COLLATE
           utf8mb3_general_ci NULL, CHANGE `bank` `bank` VARCHAR(100) CHARACTER SET utf8mb3 COLLATE
           utf8mb3_general_ci NULL, CHANGE `bankacc` `bankacc` VARCHAR(100) CHARACTER SET utf8mb3
           COLLATE utf8mb3_general_ci NULL, CHANGE `routing` `routing` VARCHAR(255) CHARACTER SET utf8mb3
           COLLATE utf8mb3_general_ci NULL, CHANGE `automaticpay` `automaticpay` INT NULL, CHANGE
           `paymentday` `paymentday` DATE NULL, CHANGE `cardexp` `cardexp` DATE NULL, CHANGE `w2principal`
           `w2principal` INT NULL, CHANGE `w2conyugue` `w2conyugue` INT NULL, CHANGE `paymentconf`
           `paymentconf` VARCHAR(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `tipoclient`
           `tipoclient` INT NULL, CHANGE `fechacreado` `fechacreado` DATE NULL, CHANGE `nameinsurance`
           `nameinsurance` VARCHAR(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL, CHANGE `acepto`
           `acepto` INT NULL, CHANGE `unemprincipal` `unemprincipal` INT NULL, CHANGE `unemconyugue`
           `unemconyugue` INT NULL, CHANGE `id_event` `id_event` INT NULL, CHANGE `fechaInsert` `fechaInsert`
           DATE NULL, CHANGE `hora` `hora` TIME NULL, CHANGE `worked_by` `worked_by` VARCHAR(50) CHARACTER SET
           utf8mb3 COLLATE utf8mb3_general_ci NULL;
        """,
            reverse_sql="""
            
        """,
        ),
        migrations.RunSQL(
            """
           ALTER TABLE `client_parient` CHANGE `names` `names` VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
           CHANGE `lastnames` `lastnames` VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL, CHANGE `date_brith`
           `date_brith` DATE NULL, CHANGE `coverrage` `coverrage` CHAR(1) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
           CHANGE `id_status` `id_status` INT(15) NULL, CHANGE `social_security` `social_security` VARCHAR(15) CHARACTER SET latin1
           COLLATE latin1_swedish_ci NULL, CHANGE `alien` `alien` VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL,
           CHANGE `card` `card` VARCHAR(50) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL, CHANGE `src` `src` VARCHAR(50)
           CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL, CHANGE `catagory` `catagory` VARCHAR(50) CHARACTER SET latin1 COLLATE
           latin1_swedish_ci NULL, CHANGE `fechaexdition` `fechaexdition` DATE NULL, CHANGE `folio` `folio` VARCHAR(50) CHARACTER
           SET latin1 COLLATE latin1_swedish_ci NULL, CHANGE `depature` `depature` VARCHAR(50) CHARACTER SET latin1 COLLATE
           latin1_swedish_ci NULL, CHANGE `sexo` `sexo` INT(255) NULL, CHANGE `cardexp` `cardexp` DATE NULL, CHANGE `pos` `pos` INT(1) NULL;
        """,
            reverse_sql="""
            
        """,
        ),
        migrations.RunSQL(
            """
           ALTER TABLE `pending_documents` CHANGE `id_tipopendoc` `id_tipopendoc` INT(15) NULL, CHANGE `upload_date`
           `upload_date` DATE NULL, CHANGE `end_date` `end_date` DATE NULL, CHANGE `nota` `nota` VARCHAR(255) CHARACTER SET
           latin1 COLLATE latin1_spanish_ci NULL;
        """,
            reverse_sql="""
            
        """,
        ),
        migrations.RunSQL(
            """
           ALTER TABLE `claim` CHANGE `finished` `finished` INT(1) NULL, CHANGE `note_responce` `note_responce` TEXT
           CHARACTER SET utf8 COLLATE utf8_general_ci NULL;
        """,
            reverse_sql="""
            
        """,
        ),
        migrations.RunSQL(
            """
           ALTER TABLE `claim` ADD `seen` INT NULL default 0 AFTER `file`;
           ALTER TABLE claim MODIFY COLUMN months VARCHAR(50) null;
           update claim set seen = 1 where finished = 1;
        """,
            reverse_sql="""
            
        """,
        ),
        migrations.RunSQL(
            """
           ALTER TABLE `claim` CHANGE `menber_number` `menber_number` INT(9) NULL;
           ALTER TABLE `claim` ADD `id_insured` INT NULL DEFAULT NULL AFTER `seen`;
        """,
            reverse_sql="""
            
        """,
        ),
        migrations.RunSQL(
            """
           update payments_global p set p.info_month = concat(p.month,'/01/',p.pyear) where p.info_month is null
        """,
            reverse_sql="""
            
        """,
        ),
    ]
